import React, { useEffect, useState } from "react";
import ProCard from "../../components/ProCard";
import { useAuth } from "../../contexts/AuthContext";
import { jsPDF } from "jspdf";
import { BASE_API } from "../../api";

export default function StudentDashboard() {
  const { user } = useAuth();
  const [feeDetails, setFeeDetails] = useState(null);
  const [room, setRoom] = useState("Not assigned");

  const downloadReceipt = async () => {
    if (!user || !user.id) return alert("User ID missing");

    try {
      const res = await fetch(`${BASE_API}/student/fee_receipt/${user.id}`);
      const data = await res.json();

      if (!res.ok) {
        alert(data.detail || "No paid transaction found");
        return;
      }

      const receipt = data.receipt;
      const doc = new jsPDF();

      // 🏫 Add headings
      doc.setFont("helvetica", "bold");
      doc.setFontSize(22);
      doc.text("Madras Institute of Technology", 35, 20);

      doc.setFont("helvetica", "normal");
      doc.setFontSize(14);
      doc.text("Generated by MIT Hostel Management System", 45, 28);

      doc.setFont("helvetica", "bold");
      doc.setFontSize(18);
      doc.text("Hostel Fee Payment Receipt", 75, 40);

      // 📄 Add details
      doc.setFont("helvetica", "normal");
      doc.setFontSize(12);
      doc.text(`Transaction ID: ${receipt.transaction_id}`, 20, 60);
      doc.text(`Student Name: ${receipt.student_name}`, 20, 70);
      doc.text(`Email: ${receipt.email}`, 20, 80);
      doc.text(`Program: ${receipt.program}`, 20, 90);
      doc.text(`Semester: ${receipt.semester}`, 20, 100);
      doc.text(`Amount Paid: ₹${receipt.amount}`, 20, 110);
      doc.text(`Date: ${receipt.date}`, 20, 120);
      doc.text(`Status: ${receipt.status}`, 20, 130);

      doc.text("Thank you for your payment!", 20, 150);

      doc.save(`Fee_Receipt_${receipt.transaction_id}.pdf`);
    } catch (err) {
      console.error("Error fetching receipt:", err);
      alert("Failed to fetch or generate receipt");
    }
  };

  useEffect(() => {
    if (!user || !user.id) return;

    fetch(`${BASE_API}/api/hostel_fee/${user.id}`)
      .then((res) => res.json())
      .then((data) => setFeeDetails(data))
      .catch((err) => console.error("Error fetching fee details:", err));
    
    fetch(`${BASE_API}/api/rooms`)
      .then((res) => res.json())
      .then((data) => {
        const rooms = data.rooms || [];
        for (const r of rooms) {
          if (r.students.some((s) => s.id === user.student_id)) {
            setRoom(r.room_number);
            break;
          }
        }
      });
      
  }, [user]);

  if (!user) return <div>Please login to view your dashboard.</div>;

  const handlePayment = async () => {
    try {
      const res = await fetch(`${BASE_API}/api/pay_hostel_fee/${user.id}`, {
        method: "POST",
      });
      const data = await res.json();

      if (res.ok) {
        alert(data.message || "Payment successful!");
        const updated = await fetch(`${BASE_API}/api/hostel_fee/${user.id}`);
        const newData = await updated.json();
        setFeeDetails(newData);
      } else {
        alert(data.detail || "Payment failed.");
      }
    } catch (err) {
      console.error(err);
      alert("Error processing payment.");
    }
  };

  return (
    <div className="container py-4">
     

      <div className="row g-3">
        {/* 👤 PROFILE CARD */}
        <div className="col-lg-4">
          <ProCard id="profile" title="Profile">
            <p><strong>ID:</strong> {user.id || "Unknown"}</p>
            <p><strong>Name:</strong> {user.username || "Unknown"}</p>
            <p><strong>Email:</strong> {user.email || "Unknown"}</p>
            <p><strong>Room:</strong> {user.room_id || "Not assigned"}</p>
            <p><strong>Phone:</strong> {user.phone || "Unknown"}</p>
            <p><strong>Semester:</strong> {user.semester || "Unknown"}</p>
            <p><strong>Program:</strong> {user.Program || "Unknown"}</p>
          </ProCard>
        </div>

        {/* 💰 FEE CARD */}
        <div className="col-lg-4">
          <ProCard id="fee" title="Fee Details">
            {console.log('fee',feeDetails)}
            {!feeDetails ? (
              <p>Loading fee details...</p>
            ) : feeDetails.error ? (
              <p className="text-danger">{feeDetails.error}</p>
            ) : (
              <>
                <p><strong>Status:</strong> {feeDetails.status}</p>
                <p><strong>Deadline:</strong> {feeDetails.deadline}</p>
                <p><strong>Fee Amount:</strong> ₹{feeDetails.fee_amount}</p>
                <p><strong>Fine (per day):</strong> ₹{feeDetails.fine}</p>
                <p><strong>Total Payable:</strong> ₹{feeDetails.total_payable}</p>

                <div className="d-flex gap-2 mt-3">
                  {feeDetails.status === "Paid" ? (
                    <button className="btn btn-success btn-sm w-50" disabled>
                      Paid
                    </button>
                  ) : (
                    <button className="btn btn-primary btn-sm w-50" onClick={handlePayment}>
                      Pay Now
                    </button>
                  )}
                  <button
                    className="btn btn-outline-secondary btn-sm w-50"
                    onClick={downloadReceipt}
                  >
                    Download Receipt
                  </button>
                </div>
              </>
            )}
          </ProCard>
        </div>

        {/* 🚪 GATE PASS CARD */}
        <div className="col-lg-4">
          <ProCard id="gatepass" title="Gate Pass">
            <div className="d-flex flex-column gap-2">
              <a className="btn btn-outline-primary btn-sm" href="/student/gatepasses">
                ➕ Submit Gate Pass Application
              </a>
              <a className="btn btn-outline-info btn-sm" href="/student/gatepass/status">
                📄 View Gate Pass Status
              </a>
            </div>
          </ProCard>
        </div>

        {/* 📢 RECENT NOTICES */}
        <div className="col-12">
          <ProCard title="Recent Notices">
            <ul className="list-group">
              <li className="list-group-item">
                Welcome to the hostel portal — keep your documents updated.
              </li>
              <li className="list-group-item">
                Mess schedule updated for the next week.
              </li>
              <li className="list-group-item">
                Fee payment deadline approaching soon — avoid fines.
              </li>
            </ul>
          </ProCard>
        </div>
      </div>
    </div>
  );
}
